//  Here we are using named export

export const restaurantList = [
  {
    info: {
      id: "255655",
      name: "Cake & Cream",
      cloudinaryImageId: "421458f15518deb6eb09a6f168daaf4b",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastry", "Cake"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "30",
    },
  },
  {
    info: {
      id: "350363",
      name: "Haldiram's Sweets and Namkeen",
      cloudinaryImageId: "ixpxqsjrymsxgmt0cvlp",
      avgRating: 4.6,
      veg: true,
      cuisines: ["North Indian", "South Indian", "Chinese"],
      parentId: "391465",
      avgRatingString: "4.6",
      totalRatingsString: "100+",
      delivery_time: "10",
    },
  },
  {
    info: {
      id: "154891",
      name: "Rasraj Restaurant",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/7f76a072-c1bc-4d74-ac56-33e0eea20c1e_5934.JPG",
      locality: "Civil Line",
      areaName: "Civil Lines",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian", "South Indian", "Street Food"],
      avgRating: 4.2,
      delivery_time: "38",
    },
  },
  {
    info: {
      id: "798745",
      name: "Friends Restaurant",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/7/23/de65f25e-2111-47fb-95e0-014bc185b007_15a51220-fdf5-4e4f-8cc6-a45c29edfc1d.JPG",
      locality: "Gayatri Nagar",
      areaName: "Jairaj Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Biryani"],
      avgRating: 4.2,
      parentId: "84308",
      delivery_time: "18",
    },
  },
  {
    info: {
      id: "314737",
      name: "RASOI the KITCHEN",
      cloudinaryImageId: "lvvv1gtajlp7y5msjrjb",
      locality: "Sriram Chowk",
      areaName: "Bazar Ward",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Maharashtrian", "Chinese", "Thalis"],
      avgRating: 3.9,
      parentId: "167341",
      delivery_time: "45",
    },
  },
  {
    info: {
      id: "201454",
      name: "Morsels Restaurants",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/3/29/09faf355-4d13-4a7f-a56a-aba5ccc6f0b2_ea23940d-f491-45d7-98fd-fbdf04d6075f.jpg",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "South Indian"],
      avgRating: 3.2,
      veg: true,
      parentId: "139266",
      avgRatingString: "4.2",
      delivery_time: "33",
    },
  },
  {
    info: {
      id: "266124",
      name: "Trimurti Restaurant",
      cloudinaryImageId: "z4qvgz4pwapyi3uglys7",
      locality: "Bazar Ward",
      areaName: "Chandrapur Locality",
      costForTwo: "₹150 for two",
      cuisines: ["Desserts"],
      avgRating: 3.9,
      veg: true,
      parentId: "217751",
      avgRatingString: "4.4",
      delivery_time: "26",
    },
  },
  {
    info: {
      id: "509254",
      name: "Saha Restaurant",
      cloudinaryImageId: "z1ez4uc9idul2uj2v87g",
      areaName: "Jairaj Nagar",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Biryani", "Thalis", "Beverages"],
      avgRating: 3.7,
      parentId: "174585",
      avgRatingString: "3.7",
      delivery_time: "19",
    },
  },
  {
    info: {
      id: "255955",
      name: "Meghana Foods",
      cloudinaryImageId: "iivuhjc2mswi9lublktf",
      areaName: "Jairaj Nagar",
      costForTwo: "₹700 for two",
      cuisines: ["Biryani", "South Indian", "Thalis"],
      avgRating: 4.7,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "21",
    },
  },
  {
    info: {
      id: "255785",
      name: "Donne Biriyani",
      cloudinaryImageId: "d26bca0145c805ef8642fad5a3ab26a0",
      areaName: "Jairaj Nagar",
      costForTwo: "₹800 for two",
      cuisines: ["Biriyanis", "South Indian", "Thalis"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "20",
    },
  },
  {
    info: {
      id: "567812",
      name: "Spice Junction",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/8/25/4b709b40-3a7b-4b50-a0ec-61c3938db216_3d6424d9-4a78-4917-8ba6-59d25cd48145.JPG",
      areaName: "Sector 15",
      costForTwo: "₹350 for two",
      cuisines: ["Indian", "Mughlai", "Seafood"],
      avgRating: 4.5,
      delivery_time: "25",
    },
  },
  {
    info: {
      id: "678921",
      name: "Biryani Hub",
      cloudinaryImageId: "h1ymnuqmffsvzoesdlnd",
      areaName: "Downtown",
      costForTwo: "₹280 for two",
      cuisines: ["Biryani", "Kebabs", "Hyderabadi"],
      avgRating: 4.6,
      delivery_time: "20",
    },
  },
  {
    info: {
      id: "789231",
      name: "Pasta & More",
      cloudinaryImageId: "39e0ac9e01e139dd8c50aa35fddead14",
      areaName: "Central Mall",
      costForTwo: "₹300 for two",
      cuisines: ["Italian", "Pasta", "Pizza"],
      avgRating: 4.3,
      delivery_time: "28",
    },
  },
  {
    info: {
      id: "894563",
      name: "Sushi House",
      cloudinaryImageId: "e7ee90a0ab15af21c18b27b6a2468dd8",
      areaName: "Metro Square",
      costForTwo: "₹400 for two",
      cuisines: ["Japanese", "Sushi", "Ramen"],
      avgRating: 4.7,
      delivery_time: "35",
    },
  },
  {
    info: {
      id: "255701",
      name: "Bobba Bhai",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/7/813c82af-f673-4609-aeaf-bc019d274998_819617.jpg",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Burger", "Ice Tea"],
      avgRating: 3.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "12",
    },
  },
  {
    info: {
      id: "255695",
      name: "Rolls and Bowls Company",
      cloudinaryImageId: "b76ea4dabf81247077db6a0b0286c145",
      areaName: "Jairaj Nagar",
      costForTwo: "₹600 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastry", "Cake"],
      avgRating: 4.7,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "39",
    },
  },
  {
    info: {
      id: "255308",
      name: "Mc Donald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/18/edc568f6-6813-4f2d-a670-911788f1f04f_23678.jpg",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Burger", "Fast Food", "Beverages"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "10",
    },
  },
  {
    info: {
      id: "255903",
      name: "Kottayam Kerala Foods",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/13/d67b450e-fb84-4c42-b498-1bca7efe3629_564070%20(1).jpg",
      areaName: "Jairaj Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["South Indian", "Kerala", "Thalis"],
      avgRating: 4.1,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
      delivery_time: "25",
    },
  },
];
